# Generated by Django 3.2.9 on 2021-12-04 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Username',
            new_name='username',
        ),
    ]
